packages:
  - 'packages/*'
  - 'playground'
  - 'runtime/*'
  - 'vue-components/*'
  - 'react-components/*'
  - 'eslint-config'

catalog:
  vue: ^3.5.22
  '@vue/compiler-sfc': ^3.5.22
  vite: ^7.1.9
  typescript: "^5.9.3"
  