packages:
  - 'packages/*'
  - 'playground'
  - 'runtime/*'
  - 'vue-components/*'
  - 'react-components/*'
  - 'eslint-config'

catalog:
  vue: ^3.5.21
  '@vue/compiler-sfc': ^3.5.20
  vite: ^7.1.5
  typescript: "^5.9.2"
  